name: static-website-ci-cd

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
jobs:

    sync-to-s3:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.5
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume:
                ROLE ARN HERE # need to put here role arn after role is created 
            aws-region: us-east-1  # needs to change to the correct region

        - name: Get list of changed files # insert all the changed files in to file 
          id: changed-files
          run: |
            git fetch origin main
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
            echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
        
        - name: Sync to S3 # need to change bucket name
          run: |
            CHANGED_FILES=${{ env.changed_files }}
            for file in $CHANGED_FILES; do
                aws s3 cp "$file" "s3://bucket-name/$file" 
            done


        - name: invalidate-cache
          run: aws cloudfront create-invalidation --distribution-id distribution_ID --paths "/*" #needs to change the ditribution_id and the actual path

    